<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \App\Model\Course[] $courses
 */
?>
<form action="<?= $this->url('student', ['action' => 'save']) ?>" class="form-horizontal" method="post">
    <legend>Create new record</legend>
    <div class="form-group">
        <label for="name" class="control-label col-sm-2">Name</label>

        <div class="controls col-sm-6">
            <input type="text" class="form-control" name="name" id="name" />
        </div>
    </div>

    <div class="form-group">
        <label for="course" class="control-label col-sm-2">Course</label>

        <div class="controls col-sm-6">
            <select name="course" id="course" class="form-control">
                <option>-- Choose course --</option>
                <?php if (count($courses)) :  ?>
                    <?php foreach ($courses as $course): ?>
                        <option value="<?=$course->getId()?>"><?=$course->getName()?></option>
                    <?php endforeach; ?>
                <?php endif; ?>
            </select>
        </div>
    </div>

    <div class="form-group">
        <div class="controls col-sm-6 col-sm-offset-2">
            <button type="submit" class="btn btn-default">Submit</button>
        </div>
    </div>
</form>
